### ISSUE TITLE
CUDA not detecting my GPU

### ISSUE THREAD

**Issue by abdullahkhalid00** [rudymohammadbali/Real-time-STT#2]
I am trying to run `main.py` for `cuda` but it keeps giving me the following error(s).

```bash
E:\Real-time-STT\main.py:39: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self.thread.setDaemon(True)
Ready!

Exception in thread Thread-2 (transcribe):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Real-time-STT\main.py", line 54, in transcribe
    for segment in segments:
  File "e:\Real-time-STT\.venv\Lib\site-packages\faster_whisper\transcribe.py", line 1106, in restore_speech_timestamps
    for segment in segments:
  File "e:\Real-time-STT\.venv\Lib\site-packages\faster_whisper\transcribe.py", line 511, in generate_segments
    encoder_output = self.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^
  File "e:\Real-time-STT\.venv\Lib\site-packages\faster_whisper\transcribe.py", line 762, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
```

Here's my `pip freeze`.

```bash
av==11.0.0
certifi==2024.7.4
charset-normalizer==3.3.2
colorama==0.4.6
coloredlogs==15.0.1
ctranslate2==4.0.0
cuda-python==12.5.0
faster-whisper==1.0.1
filelock==3.15.4
flatbuffers==24.3.25
fsspec==2024.6.1
huggingface-hub==0.23.4
humanfriendly==10.0
idna==3.7
Jinja2==3.1.3
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.4
onnxruntime==1.18.1
packaging==24.1
pillow==10.2.0
protobuf==5.27.2
PyAudio==0.2.14
pyreadline3==3.4.1
PyYAML==6.0.1
requests==2.32.3
SpeechRecognition==3.10.1
sympy==1.13.0
tokenizers==0.15.2
torch==2.0.0+cu118
torchaudio==2.0.1+cu118
torchvision==0.15.1+cu118
tqdm==4.66.4
typing_extensions==4.12.2
urllib3==2.2.2
```

I'm using CUDA 12.5 Toolkit which I download from [here](https://developer.nvidia.com/cuda-downloads). Here's the output of `nvcc --version`.

```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_03:03:05_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```

Here's the output of my `nvidia-smi`.

```bash
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce 940MX         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8             N/A /  200W |       0MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

Please provide guidance on this. The program works on `cpu` but the latency is really large. Let me know if you require anything else from my side. Thanks.

**Comment by rudymohammadbali** [comment]
### Hmm, try clean install:

Make sure you have installed python version: 3.8
1. Create virtual environment, and activate it:
```
python -m venv /path/to/new/virtual/environment
```

2. Download Real-time-STT from GitHub:
```
git clone https://github.com/rudymohammadbali/Real-time-STT.git
cd Real-time-STT
```

3. Install requirements:
```
pip install -r requirements.txt
```
4. Install CUDA version: 11.8:
```
pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
```

5.  Download and install CUDA toolkit version: 12.5, and NVIDIA libraries:

https://developer.nvidia.com/cuda-downloads

https://developer.nvidia.com/cublas

https://developer.nvidia.com/cudnn

### Tell me if it worked!

**Comment by rudymohammadbali** [comment]
Your GPU only has 2GB of memory, so only small model is available!

**Comment by abdullahkhalid00** [comment]
### It still shows me the same error.

What I did:

 - I installed Python 3.8.0
 - Cloned the repo and reinstalled requirements.txt
 - Reinstalled CUDA 11.8, the CUDA Toolkit 12.5 and cuDNN

About your last comment, would I get low latency on GPU even if I run `tiny.en` or `base.en`? Right now on my CPU, I'm running `tiny.en` and it sometimes does not show me any output at all.

**Comment by rudymohammadbali** [comment]
I might have found solution try:
```

pip install ctranslate2==3.24.0

```

**Comment by rudymohammadbali** [comment]
Check out

https://github.com/SYSTRAN/faster-whisper

For more information about models and requirements, also check issues page and look for others solutions.

**Comment by abdullahkhalid00** [comment]
> I might have found solution try:
> 
> ```
> 
> pip install ctranslate2==3.24.0
> ```

This worked for me. Thanks a lot and apologies for not posting sooner.
